### ISSUE TITLE
Re-enable scanning for SBOM records in Docker image

### ISSUE THREAD

**Issue by nycnewman** [docker/buildkit-syft-scanner#111]
In a slightly dated Docker Blog post, it was highlighted that you could add SBOM details for any binaries added manually to a Docker image:

https://www.docker.com/blog/generate-sboms-with-buildkit/

This was broken some time back apparently and the blog also references a snippet that does not work (need to be a full SBOM package record).

Syft maintainers suggested a minor fix to re-enable this feature:

https://github.com/docker/buildkit-syft-scanner/blob/f22f9866c24554ba087f5798d03a41c39f3e5f7b/internal/target.go#L49

syft.CreateSBOM(context.Background(), nil, syft.DefaultCreateSBOMConfig().
	WithCatalogerSelection(pkgcataloging.NewSelectionRequest().
		WithDefaults(pkgcataloging.ImageTag).
+ 			WithAdditions("sbom-cataloger"),
	),
)

Full discussion with Syft is here:

https://github.com/anchore/syft/issues/3490#issuecomment-2511860821

**Comment by jedevc** [comment]
Hm, we should also have had tests for this case.

**Comment by nycnewman** [comment]
Tried to create a PR but hit a ton of issues (as I'm not a GoLang expert) with Syft and case of "microsoft" vs "Microsoft" in Syft dependencies. Since this project pulls in both github.com/Microsoft and github.com/microsoft, it picks capitalized version and fails on syft dependencies.

**Comment by nycnewman** [comment]
Similar issue to https://github.com/anchore/syft/issues/2026

**Comment by cdupuis** [comment]
This is now fixed in master via #115.
